name: Build python
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full tar msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint gcc-11
    - name: Clone source code
      run: |
        curl -L -O https://www.python.org/ftp/python/3.9.16/Python-3.9.16.tar.xz
        tar xf ./Python-3.9.16.tar.xz
    - name: Build
      run: |
        cd ./Python-3.9.16
        configure --enable-optimizations
        make -j$(nproc)
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
