name: Build python
on:
  push:

jobs:
  build_ubuntu:
    name: 'Ubuntu'
    runs-on: ubuntu-20.04
    steps:
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential git libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev libgdbm-dev libgdbm-compat-dev gcc-11
    - name: Clone source code
      run: |
        git clone -b v3.9.16 https://github.com/python/cpython
    - name: Build
      run: |
        cd ./cpython
        ./configure --enable-optimizations --prefix=/home/runner/work/python-build/python
        make -j$(nproc)
        make install
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: python-build-linux-amd64-3.9.16
        path: /home/runner/work/python-build/python
  
