name: Build python
on: push
jobs:
  build_linux:
    runs-on: ubuntu-latset
    steps:
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential git libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev libgdbm-dev libgdbm-compat-dev gcc-11
    - name: Clone source code
      run: |
        git clone -b v3.9.16 https://github.com/python/cpython
    - name: Build
      run: |
        cd ./cpython
        ./configure --enable-optimizations --prefix=/home/runner/work/python-build/python
        make -j$(nproc)
        make install
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: python-build-linux-3.9.16
        path: /home/runner/work/python-build/python
  build_win_amd64:
    name: 'Windows (x64)'
    runs-on: windows-latest
    #needs: check_source
    #if: needs.check_source.outputs.run_tests == 'true'
    env:
       IncludeUwp: 'true'
    steps:
    - uses: actions/checkout@v3
    - name: Register MSVC problem matcher
      run: echo "::add-matcher::.github/problem-matchers/msvc.json"
    - name: Build CPython
      run: |
        pip install -U mercurial
        git clone -b v3.9.16 https://github.com/python/cpython
        cd python
        mkdir .\build
        .\Tools\msi\buildrelease.bat -x64 -D -B --skip-nuget -o D:\a\cpython\cpython\build
     - name : Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-build-win-amd64-3.12a5   
        path: D:\a\cpython\cpython\PCbuild\amd64\en-us
